### ISSUE TITLE
how is MDMCM in curvature_utils.py different from DMCM 

### ISSUE THREAD

**Issue by bootsmakes** [ideas-man/curvature-embedding#1]
Hello,
How is MDMCM in curvature_utils.py different from DMCM detailed in Cohen-Steiner and Morvan?

**Comment by ideas-man** [comment]
Hi @bootsmakes!

It was a long time ago, but by comparison with the original trimesh implementation [here](https://github.com/mikedh/trimesh/blob/main/trimesh/curvature.py#L87) the difference is contained in [these](https://github.com/ideas-man/curvature-embedding/blob/master/curvature_utils.py#L33-L38) lines. As far as I can remember (and how the [docstring](https://github.com/ideas-man/curvature-embedding/blob/master/curvature_utils.py#L12) for my function suggests), I am limiting the angles contributing to the overall measure to only the 1-ring neighborhood edges, instead of using all angles at all edges that are contained in the query ball.

Hope this helps.
